name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main' # Trigger on pushes to the main branch
  release:
    types: [published] # Trigger on new releases

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Specifies the build context, where the Dockerfile is located
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
